### ISSUE TITLE
[FEATURE] Close preview with standard keys

### ISSUE THREAD

**Issue by lougreenwood** [rmagatti/goto-preview#57]
**Is your feature request related to a problem? Please describe.**
I use goto preview to "peek" definitions described in https://github.com/rmagatti/goto-preview/issues/44. In these cases my muscle memory is to close popovers with `c-[` (or alternatively `esc` or `c-c`, etc).

**Describe the solution you'd like**
A config option that allows the popover to be closed using the usual vim keys for closing popovers or menus

**Describe alternatives you've considered**
Creating my own mappings - but figured this might be a useful feature to compliment https://github.com/rmagatti/goto-preview/issues/44

**Comment by rmagatti** [comment]
> to be closed using the usual vim keys for closing popovers or menus

I'm not sure this is true, as in you might be thinking of popovers in insert mode like completion menus that disappear when you hit `<Esc>`, those disappear because you've left insert mode most likely, not because it's listening for `<Esc>`.

I myself would find it ergonomically awkward if `<Esc>` suddenly closed a peak window instead of just doing what it normally does.
Plus one might want to go into the peak window to do a quick edit, in which case they'd undoubtedly need to hit the `<Esc>` key to switch modes and then the peak window would just disappear, instead of going into normal mode so they can save their edit.

**Comment by rmagatti** [comment]
Stale.
