### ISSUE TITLE
Support for opening in current window

### ISSUE THREAD

**Issue by sahilsehwag** [rmagatti/goto-preview#6]
It would be great, if an additional command/function/mapping can be provided that opens the preview in active topmost window, so that we can choose if we want to open the next preview in same window or in a new one, since sometimes we encounter some symbols  that we know we want to skip and go inside.

This would satisfy another usecase where we just want to go inside to find a specific symbol without opening a lot of buffers or a lot of floating windows(flow is kind of like vscode where we can open a file and jump to different locations and it will change the buffer in the same window, unless we double click, kind of like transient buffer)

**Comment by rmagatti** [comment]
Hey @sahilsehwag, thank you for the submission!

I'm not sure I quite understand what you're proposing though, I'll try and address a few points.

> opens the preview in active topmost window

By design, at least currently, previews open in floating windows, you _can_ manipulate these windows just like normal windows, so you can move the preview to a split. Pending the weird UI issues that happen when you do that, I think this covers it

> This would satisfy another usecase where we just want to go inside to find a specific symbol without opening a lot of > buffers or a lot of floating windows(flow is kind of like vscode where we can open a file and jump to different locations and it will change the buffer in the same window, unless we double click, kind of like transient buffer)

This is actually already the case, if you trigger the regular goto definition from within a preview buffer, you'll just navigate to it without opening a nested preview. Unless I misunderstood you?
